### ISSUE TITLE
Outdated version in configure.ac and debian/changelog

### ISSUE THREAD

**Issue by n-st** [shellinabox/shellinabox#347]
The v2.18 release still has the old version number and changelog from v2.17, so a Debian package built from that release will not be considered an upgrade by dpkg.

**Comment by KLuka** [comment]
Thanks for heads up :+1: Do you experience any problems because of this issue?

Release 2.18 was created for Fedora package and it won't be released to official Debian repository. I added this info to release page just now. 

I am not sure how to correctly handle this type of releases. Should we update Debian changelog anyway? Do you have any clue? Or maybe @a-detiste and @beewoolie can help on this one...

**Comment by beewoolie** [comment]
I'm a little confused.  What is the question?

**Comment by n-st** [comment]
Keeping the version number unchanged between releases breaks most reasonable assumptions about update cycles. I was hoping I could just build packages from the release tags to stay up-to-date, but since release 2.17 and 2.18 create identical Debian packages, the package won't be updated to the newly built version.

Besides, I just noticed that I built my current package from master's HEAD instead of a release tags, so I now have a package with the version string 2.17 that contains a binary that self-identifies as version 2.19:

    $ apt-cache policy shellinabox 
    shellinabox:
      Installed: 2.17
      Candidate: 2.17
      Version table:
     *** 2.17 0
            500 http://packages.voidptr.de/ wheezy/main amd64 Packages
            100 /var/lib/dpkg/status
         2.14-1 0
            500 http://ftp.de.debian.org/debian/ wheezy/main amd64 Packages
           -1000 http://ftp.de.debian.org/debian/ jessie/main amd64 Packages
    $ shellinaboxd -v
    [server] Version 2.19 (revision 973f152)
    [server] Command line: shellinaboxd -v 
    [server] Failed to find any available port!


Perhaps you could add the build date and git hash to the package version to be able to discern packages built from code revisions that haven't had their version string changed yet?

**Comment by beewoolie** [comment]
So, did we just make a mistake when we released in that we failed to 
update all of the places where the version number is set.  I know that 
the versions has become quite a mess with packages that use autoconf 
because there are so many places where the number is stored.  If this is 
just a matter of making the correct patch and updating *all* of the 
versions then that seems like the right thing to do.

**Comment by KLuka** [comment]
> Since releases 2.17 and 2.18 create identical Debian packages, the package won't be updated to the newly built version.

If you are manually installing `.deb` package with `dpkg -i` this should not be a problem. It will correctly update all shellinabox files...

> Also, building a package from master's HEAD leaves you with a package with version number 2.17...

Yes this is because of debian/changelog file has not been updated. Maybe a solution would be to update changelog file with something like this, after each Github release that won't be pushed to official Debian repo:
```
shellinabox (2.18) UNRELEASED; urgency=medium

  * Non-maintainer upload.
  ...
```

> ...that contains a binary that self-identifies as version 2.19.

I started updating version in configure.ac after each Github release. This way users are aware that they are using sources for latest version, that has not been officially tagged yet.

**Comment by KLuka** [comment]
> If this is just a matter of making the correct patch and updating *all* of the versions then that seems like the right thing to do.

Would that mean that version should be somehow automaticaly inserted in debian/changelog?

**Comment by beewoolie** [comment]
If I understand you correctly, there are changes in the repo that 
haven't been pushed to the archive.  If this is true, it probably is 
best to release them if they are something people want to use.

As for changing debian/changelog without making a release, this is not 
usually a good idea. We already did this once before and it creates a 
real hassle because we have to update the release number again before 
release to guarantee that the package will update on systems that had 
pulled from the repo.

If you want to make a change to changelog it would be must better to 
change the release to 2.17-1 or something that will be overwritten by a 
Debian release.

As for the comment below about 2.18, I'm still confused.  The latest is 
2.17, isn't it?  Where does 2.18 come from?

**Comment by KLuka** [comment]
> If I understand you correctly, there are changes in the repo that haven't been pushed to the archive.

Yes this is true :smile:

> As for changing debian/changelog without making a release, this is not usually a good idea...

I remember that. But I think that, if that version is really not pushed to Debian problems won't occur. For example this is the current situation:
* v2.17 - latest Debian release
* v2.18 - latest Fedora release (not for Debian, but we update debian/changelog anyway)
* v2.19 - future Debian release

Would that work?

> As for the comment below about 2.18, I'm still confused. The latest is 2.17, isn't it? Where does 2.18 come from?

I tagged version 2.18 here on Github, so it could be used for Fedora package release. See here: https://github.com/shellinabox/shellinabox/releases

**Comment by beewoolie** [comment]
On 9/15/15 12:44 PM, Luka Krajger wrote:
>
>     If I understand you correctly, there are changes in the repo that
>     haven't been pushed to the archive.
>
> Yes this is true :smile:
>
>     As for changing debian/changelog without making a release, this is
>     not usually a good idea...
>
> I remember that. But I think that, if that version is really not 
> pushed to Debian problems won't occur. For example this is the current 
> situation:
>
>   * v2.17 - latest Debian release
>   * v2.18 - latest Fedora release (not for Debian, but we update
>     debian/changelog anyway)
>   * v2.19 - future Debian release
>
> Would that work?
>

Oh, sure.  No one cares about the continuity of the version numbers.

>     As for the comment below about 2.18, I'm still confused. The
>     latest is 2.17, isn't it? Where does 2.18 come from?
>
> I tagged version 2.18 here on Github, so it could be used for Fedora 
> package release. See here: 
> https://github.com/shellinabox/shellinabox/releases
>

Ah.  I see.  Is there a structural reason to avoid a more incremental 
version number?  2.17.1?

The only risk is confusion to people who scrutinize the version 
numbers.  Someone might ask why there is a 2.17 for Debian and a 2.18 
for Fedora.  The fractional version number is *less* confusing, but 
doesn't eliminate the difference.

IMHO, there is no problem induced by a new version for Fedora.  I do 
think it is best to keep the package version numbers in sync, 
debian/changelog notwithstanding.

**Comment by n-st** [comment]
> Someone might ask why there is a 2.17 for Debian and a 2.18 for Fedora.

Agreed, that would be very confusing, if not frustrating for users that want to use the most recent version.


What's in 2.18 anyway?
If it has actual features, shouldn't there be a 2.18 release for Debian?
On the other hand, if it's just some Fedora-specific bugfix, shouldn't it have a version string like 2.17-1 (signifying that the changes it contains are distribution-specific)?

For future releases, something like the generic changelog entry KLuka suggested would probably be a good idea. Maybe it could even be generated automatically during the build process to include the build date and/or git hash it was built from, e.g. 2.19-20150915195830-973f1527bd. That would allow a clear distiction between "official" release builds and custom builds from the git repo and also make sure that more recent custom builds are actually considered to be updates by apt-get.

**Comment by beewoolie** [comment]
On 9/15/15 1:00 PM, n.st wrote:
>
>     Someone might ask why there is a 2.17 for Debian and a 2.18 for
>     Fedora.
>
> Agreed, that would be very confusing, if not frustrating for users 
> that want to use the most recent version.
>
> What's in 2.18 anyway?
> If it has actual features, shouldn't there be a 2.18 release for Debian?
> On the other hand, if it's just some Fedora-specific bugfix, shouldn't 
> it have a version string like 2.17-1 (signifying that the changes it 
> contains are distribution-specific)?
>
> For future releases, something like the generic changelog entry KLuka 
> suggested would probably be a good idea. Maybe it could even be 
> generated automatically during the build process to include the build 
> date and/or git hash it was built from, e.g. 
> 2.19-20150915195830-973f1527bd. That would allow a clear distiction 
> between "official" release builds and custom builds from the git repo 
> and also make sure that more recent custom builds are actually 
> considered to be updates by apt-get.
>
> —
>

That sounds overwrought to me.  I don't see the advantage of a long 
version string over being rigorous about when and how the version changes.

In the end, this isn't a show-stopper.  We can release 2.19 (or 
whatever) for Debian when the time comes.

**Comment by n-st** [comment]
> That sounds overwrought to me. I don't see the advantage of a long version string over being rigorous about when and how the version changes.

Since one of the suggested ways of installing shellinabox are the self-built Debian packages, there should be a way to build them with a sensible, monotonically increasing version number.
It doesn't have to be $version-$(date -u +%Y%m%d%H%M%S)-$githash, of course, but something that's guaranteed to increase monotonically would be nice. $version-$(date -u %s) perhaps?

If you decide against a way to build this kind of rolling-version .deb packages, perhaps you could create a separate branch that's only fast-forwarded to the last stable release, and change the instructions in the README to build the .deb from this separate branch, rather than master?

**Comment by KLuka** [comment]
I also don't want to complicate with this version stuff any further... this dates and other stuff in version string looks very confusing.

And as I said before command  `dpkg -i`, mentioned in README, is working just fine and all files are updated to latest version.

I think that logic described bellow should work fine:

**Github releases not intended for Debian**

* Will be tagged as 2.17.X, so that we don't confuse the users with different minor version on different systems.
* File `debian/changelog` will be updated with new version marked as `UNRELEASED`. This way manually built .deb packages will contain latest version.

**Github releases that will be pushed to Debian**

* Major/minor/patch version will be increased. This way `apt-get` will see this as a update in any case. Even for manually built packages from Github.

So I don't see anymore problems here. Do you agree?

**Comment by beewoolie** [comment]
This seems sensible to me.

The only thing that is still confusing is why would there be a new 
version of code in the repo that isn't in a Debian released package?  
Other than updates for other distributions, I don't see much reason to 
keep changes out of Debian.

IOW, why would someone manually build for Debian when the latest in the 
repo is the latest useful version for them?

**Comment by KLuka** [comment]
> The only thing that is still confusing is why would there be a new version of code in the repo that isn't in a Debian released package?

This is just for urgent cases when you won't have enough time to prepare a proper release and some other system maintainer might need it... It is just a special case, and it won't happen often...

> IOW, why would someone manually build for Debian when the latest in the repo is the latest useful version for them?

This is just for the HEAD version. Lets say that you need to test latest commits or something... I do that sometimes :smile:

**Comment by beewoolie** [comment]
Sure.  These are typical considerations.

+1 <- Your plan

:-)

**Comment by a-detiste** [comment]
Hi,

Why not get rid of this problem definitively ?

This way, a new `UNRELEASED` version is added at the top of debian/changelog
right after an official release is done.

Having release in a changelog that got skipped never ends up uploaded in the archive is not a problem.


```patch
+++ b/configure.ac
@@ -2,7 +2,9 @@ AC_PREREQ(2.57)
 
 dnl This is one of the locations where the authoritative version
 dnl  number is stored.  The other is in the debian/changelog.
-AC_INIT(shellinabox, 2.16, markus@shellinabox.com)
+AC_INIT(shellinabox,
+        m4_esyscmd_s([head -1 debian/changelog | awk -F'[()]' '{print $2}']),
+        markus@shellinabox.com)
```

**Comment by beewoolie** [comment]
Sure.  Seems reasonable to me to revise the configure.ac to pull the 
version number from the Debian changelog.

**Comment by KLuka** [comment]
> This way, a new UNRELEASED version is added at the top of debian/changelog
right after an official release is done.

But this causes that users with manually built packages, won't get updates from official Debian repo, when new version will be released. Just like it happened last time...

For now I would just stick with the original plan :wink: I updated Debian changelog so that packages built from current HEAD will contain latest version (last Github release).

Command `--version` is showing version 2.19 (latest + 1), so that users are aware that they are using officially unreleased sources.

*PS:* @beewoolie I might be a good idea, whenever you have some time, to create another official Debian releases from current HEAD :wink: 

I am closing this issue.

**Comment by beewoolie** [comment]
On 9/17/15 1:52 AM, Luka Krajger wrote:
>
>     This way, a new UNRELEASED version is added at the top of
>     debian/changelog
>     right after an official release is done.
>
> But this causes that users with manually built packages, won't get 
> updates from official Debian repo, when new version will be released. 
> Just like it happened last time...
>

I think that there are two things, perhaps.  Using the code snippet that 
was proposed, we wouldn't have to change the configure.ac file 
manually.  Instead, it stays in sync with the debian/changelog.  I'm not 
very familiar with the macros in m4, so maybe my interpretation is 
wrong.  IMHO, this would be a good thing.

> For now I would just stick with the original plan :wink: I updated 
> Debian changelog so that packages built from current HEAD will contain 
> latest version (last Github release).
>
> Command |--version| is showing version 2.19 (latest + 1), so that 
> users are aware that they are using officially unreleased sources.
>

I'll have to take a look at the source to make sure I understand. Your 
confidence suggests to me that you are comfortable with you plan and 
that's also a good thing.  :-)


> /PS:/ @beewoolie <https://github.com/beewoolie> I might be a good 
> idea, whenever you have some time, to create another official Debian 
> releases from current HEAD :wink:
>

NP.

**Comment by a-detiste** [comment]
>  manually built packages,

Using `shellinabox (2.18~unreleased) UNRELEASED; urgency=low` in changelog would do the trick.

Versions are sorted this way: 2.17 < 2.18~unreleased < 2.18

https://www.debian.org/doc/manuals/maint-guide/first.en.html#namever

> I'm not very familiar with the macros in m4

Neither am I, I combined different bits off info I found with Google, but this works.

**Comment by KLuka** [comment]
Parsing version from `debian/changelog` works fine with `dpkg-buildpackage`. But there are problems with `make` command, since `config.h` is not automatically rebuilt, when `debian/changelog` is changed. So I don't recommend using this...

As @beewoolie, suggested we can just use odd version numbers for unreleased version. Versions wit even numbers will be released to official repo. 

BTW, thanks to @beewoolie for releasing version 2.18 to debian :wink:

**Comment by beewoolie** [comment]
Do we need to make another build.  If there are files that depend on the 
version we ought to fix that.  We are using computers, after all.  :-)

**Comment by KLuka** [comment]
@beewoolie there is no need to create another build. I was just saying that solution provided by @a-detiste doesn't work nice in all cases...

But for now it is all good :+1:

**Comment by a-detiste** [comment]
Yup, don't worry, it's not that important.
