### ISSUE TITLE
Paste with the third button doesn't work in Firefox41.01

### ISSUE THREAD

**Issue by stephdl** [shellinabox/shellinabox#350]
With Linux you can copy by highlighting the text and paste it with the third button of your mouse, it is workable in Chrome, but not in Firefox. (version 41.01)
Please ask if you have any questions that I may answer.

ps: many thanks for this project !!!!

**Comment by KLuka** [comment]
Hi, thanks for the bug report :+1: Problem is also reproducible with older shellinabox versions. Did it work OK with older Firefox versions?

I need some time to check what exactly is happening here...

**Comment by stephdl** [comment]
Yes I recall that it was also not workable with other version of firefox, I used shellinabox sometime ago and I have add issues with non english keyboard, now it is workable :)....but the paste issue was already there.

**Comment by KLuka** [comment]
Middle click paste is not working on Firefox, because we are trying to paste content on non-editable element, so paste event is not triggered ([Firefox bug 846674](https://bugzilla.mozilla.org/show_bug.cgi?id=846674)). Chrome handles this without a problem.

I am not sure if it will be possible to fix this for Firefox on Linux, but I think it would be a good idea to implement middle click paste feature directly in VT100 terminal. 

This way users will be able to paste the selected content at least from shellinabox output. It will also work on other operating systems, which would be a good thing, since copy/paste features in shellinabox are not exactly user friendly.

**Comment by stephdl** [comment]
I'm fan if with any O.S we can use a copy and paste with the mouse :)

**Comment by a-detiste** [comment]
Hi,

I heard about this tool today, but this would require shellinabox to prodive an xsel-like utility.

https://github.com/mptre/yank

http://www.vergenet.net/~conrad/software/xsel/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801837

**Comment by KLuka** [comment]
Hm, @a-detiste I don't think that would help in our case...

The main problem with shellinabox is the fact that JS programs don't have access to native clipboard. This is a security precaution implemented by browsers, so that arbitrary JS script cannot inspect/modify users clipboard content.

I hope I can get patch for middle click paste out soon...

_But note that patch will only allow user to copy/paste content inside shellinabox window. Users still won't be able to use middle click to paste from notepad or some other program..._

**Comment by KLuka** [comment]
Ok, @stephdl I think that commit f67073d should handle this. Please let me know how it is working for you...
