### ISSUE TITLE
shellinabox re-login when iframe resize

### ISSUE THREAD

**Issue by locronaldo** [shellinabox/shellinabox#358]
I'm using shellinabox in iframe, when i click on a button to resize the iframe larger, shellinabox re-login, it doesn't keep current state. How can i resize the iframe and shellinabox still keeps current state?

**Comment by KLuka** [comment]
Can you please provide some code that resizes your iframe? Normally, if iframe is reloaded you will lose your current session.

**Comment by locronaldo** [comment]
I've resolved the current state issue like code below: 
`<button id="small-size"`>Small`</button`>
`<button id="large-size"`>Large`</button`>
`<iframe id="shellinabox" src="http://x.x.x.x:4200" style="width: 800px; height: 400px;"`>
`</iframe`>
```javascript
$("#small-size").click(function () {
      $('#shellinabox').attr("style", "width: 800px; height: 400px;");
}); 
$("#large-size").click(function () {
       $('#shellinabox').attr("style", "width: 1200px; height: 500px;");
}); 
```
But I type some command for example 'ifconfig' in small iframe size, then I switch large size, the cursor  does not focus in terminal, I must do click on terminal to continue typing command. I try to find shellinabox source in ubuntu to set iframe focus, but I cannot find it. How can I type command without click on terminal after resizing the iframe? 
Thanks.

**Comment by uudruid74** [comment]
My test page does not log out the user - that would be a bug.  Please verify that.  The focus issue is not a bug at all.  You need to click the iframe because you are using a button!!  A button is a focusable input element.  Clicking it steals input focus.  You have two choices to fix this.   Choose one of these:

1. In your click handler, you can call $(#shellinabox').focus() to give the focus back to your iframe because the click event just stole it.
1. Instead of using click(), instease use on('mousedown', function(e) { ...}) and then end your handler with e.preventDefault() which will stop the event from stealing focus away from another object.

And this issue can be closed I think.

**Comment by locronaldo** [comment]
@uudruid74 Thanks
