### ISSUE TITLE
ERR_EMPTY_RESPONSE via apt

### ISSUE THREAD

**Issue by maravento** [shellinabox/shellinabox#449]
**Shellinabox fail:** "ERR_EMPTY_RESPONSE" (with both: https and http)
**SO:** Ubuntu 18.04.1 LTS x64
**Fail in:** Google Chrome 70.0.3538.110 (Build oficial) (64 bits) and Firefox Quantum 63.x 
**Not fail in:** Opera 56.0.3051.104
![fail](https://user-images.githubusercontent.com/14880802/48271314-0e912800-e40a-11e8-8a0d-377eb156bd7e.png)
**Port change due to conflicts:** Default port 4200 to 4242 to avoid conflicts with [SnapWeb](https://github.com/snapcore/snapweb) (use 4200 and 4201)
**Installation method:** `sudo apt -y install shellinabox`
[**Provisional solution:**](https://www.maravento.com/2018/11/shellinabox.html)  Disable ssl (to work with only http)
`sudo vi /etc/default/shellinabox`
`SHELLINABOX_ARGS="--no-beep --disable-ssl"`

**Comment by brablc** [comment]
I believe this is problem in Chrome 70.0.3538.110.

**Comment by binary-person** [comment]
I believe this should be reopened, as this isn't fixed yet. Still errors in Chrome 72 on Chromebook.

Curl works fine with https with the k option.

**Comment by binary-person** [comment]
YAY! FINALLY. I got it now.

So basically, using different version of browsers (the lower versions of chrome especially) worked.
@brablc is partially right. It is caused by a newer version of Chrome itself, but it is not Chrome's problem necessarily.

**Cause**
The main issue is the shellinabox package. People with Ubuntu Bionic (18) will likely encounter this problem. This is because the version they are installing is `2.20build1`.

**Solution**
The solution is simple. Instead of installing `2.20build1.dsc]`, install `2.19`.
Go to https://packages.ubuntu.com/xenial/shellinabox first, then click on your architecture. Next, copy the link to the deb files, and run the following:
```
# This is for users running amd64 architecture. The mirror
# link may be outdated or your architecture may not be amd64.
# If those are the case, get a new link above
wget http://mirrors.kernel.org/ubuntu/pool/universe/s/shellinabox/shellinabox_2.19_amd64.deb
sudo dpkg -i shellinabox_2.19_amd64.deb
```
Finally a solution after a year lol.

**Comment by maravento** [comment]
Ubuntu 18.04.3 and Google Chrome Version 77.0.3865.120 (Official Build) (64 bits) works fine. I only recommend that if you use Snap Web (use ports 4200 and 4201) change port 4200 to avoid conflicts or remove web snap. (in this image i change to 4242)
![sellbox](https://user-images.githubusercontent.com/14880802/67054867-94821c80-f10b-11e9-9fef-14a6ccb874e7.png)

For more information read post: [shell in a box](https://www.maravento.com/2018/11/shellinabox.html)

**Comment by ghost** [comment]
THIS CORRECTED THE PROBLEM FOR ME  : 

To install version 2.19 properly on Debian 10 :

```sh
wget http://ftp.ch.debian.org/debian/pool/main/g/glibc/multiarch-support_2.28-10_amd64.deb
dpkg -i multiarch-support_2.28-10_amd64.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb
dpkg -i libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb 
wget http://mirrors.kernel.org/ubuntu/pool/universe/s/shellinabox/shellinabox_2.19_amd64.deb
dpkg -i shellinabox_2.19_amd64.deb
```

Then :
```sh
sudo vi /etc/default/shellinabox
SHELLINABOX_ARGS="--no-beep --disable-ssl"
```

**Comment by Leaf239** [comment]
umm, chromium 118 still have this error. i use raspberry pi zero w rev 1.1, and windows 11.
